### ISSUE TITLE
 ERROR [conf-file-poller-0] (org.apache.flume.node.AbstractConfigurationProvider.loadSinks:432)  - Sink kafka has been removed due to an error during configuration

### ISSUE THREAD

**Issue by anfengdaydayup** [yrjsg/flume-kafka#9]
27 Dec 2013 11:30:49,194 ERROR [conf-file-poller-0](org.apache.flume.node.AbstractConfigurationProvider.loadSinks:432)  - Sink kafka has been removed due to an error during configuration
kafka.common.InvalidConfigException: At least one of zk.connect or broker.list must be specified
    at kafka.producer.ProducerConfig.<init>(ProducerConfig.scala:51)
    at com.vipshop.flume.KafkaUtil.getProducer(KafkaUtil.java:43)
    at com.vipshop.flume.sink.kafka.KafkaSink.configure(KafkaSink.java:47)
    at org.apache.flume.conf.Configurables.configure(Configurables.java:41)
    at org.apache.flume.node.AbstractConfigurationProvider.loadSinks(AbstractConfigurationProvider.java:418)
    at org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(AbstractConfigurationProvider.java:103)
    at org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:140)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

**Comment by yrjsg** [comment]
You need to specify zk.connect in flume conf
